"""initial_sqlalchemy_models

Revision ID: acaf1c63ce55
Revises: 
Create Date: 2026-02-16 18:09:13.404758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acaf1c63ce55"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_fts")
    op.drop_table("message_fts_idx")
    op.drop_table("message_fts_data")
    op.drop_table("message_fts_config")
    op.drop_table("message_fts_docsize")
    op.alter_column("artifact", "artifact_id", existing_type=sa.TEXT(), nullable=False)
    op.drop_index("idx_artifact_email", table_name="artifact")
    op.drop_index("idx_artifact_run", table_name="artifact")
    op.alter_column("attachment", "id", existing_type=sa.TEXT(), nullable=False)
    op.drop_index("idx_att_msg", table_name="attachment")
    op.drop_index("idx_att_name", table_name="attachment")
    op.alter_column("automation_run", "run_id", existing_type=sa.TEXT(), nullable=False)
    op.drop_index("idx_run_email", table_name="automation_run")
    op.drop_index("idx_run_mailbox", table_name="automation_run")
    op.create_unique_constraint(
        "uq_run_mb_email_action_fp",
        "automation_run",
        ["mailbox_id", "email_id", "action_type", "input_fingerprint"],
    )
    op.alter_column(
        "classification_event",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "classification_event",
        "confidence",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.drop_index("idx_cls_msg", table_name="classification_event")
    op.drop_index("idx_cls_time", table_name="classification_event")
    op.alter_column("email", "email_id", existing_type=sa.TEXT(), nullable=False)
    op.drop_index("idx_email_org", table_name="email")
    op.drop_index("idx_email_received", table_name="email")
    op.drop_index("idx_email_thread", table_name="email")
    op.alter_column(
        "email_flag", "mailbox_email_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "email_flag",
        "has_summary",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "email_flag",
        "has_translation",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "email_flag",
        "has_extraction",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "idea", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "idea",
        "entry_level",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "idea",
        "target_level",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "idea",
        "stop_level",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "idea",
        "extracted_by",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'rules_v1'"),
    )
    op.drop_index("idx_idea_ccy", table_name="idea")
    op.drop_index("idx_idea_message", table_name="idea")
    op.drop_index("idx_idea_product", table_name="idea")
    op.drop_index("idx_idea_status", table_name="idea")
    op.drop_index("idx_idea_tenor", table_name="idea")
    op.alter_column("mailbox", "mailbox_id", existing_type=sa.TEXT(), nullable=False)
    op.drop_index("idx_mailbox_org", table_name="mailbox")
    op.alter_column(
        "mailbox_email",
        "mailbox_email_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.drop_index("idx_mb_email_email", table_name="mailbox_email")
    op.drop_index("idx_mb_email_mailbox", table_name="mailbox_email")
    op.create_unique_constraint(
        "uq_me_mb_email", "mailbox_email", ["mailbox_id", "email_id"]
    )
    op.alter_column(
        "mailbox_emails",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "mailbox_emails",
        "seen",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "mailbox_emails",
        "processed",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index("idx_mb_processed", table_name="mailbox_emails")
    op.create_unique_constraint(
        "uq_mbe_mb_canonical", "mailbox_emails", ["mailbox_id", "canonical_key"]
    )
    op.alter_column("message", "id", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "message",
        "urgency",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'none'"),
    )
    op.alter_column(
        "message",
        "has_attachment",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index("idx_message_received", table_name="message")
    op.drop_index("idx_msg_thread", table_name="message")
    op.drop_index("idx_msg_urgency", table_name="message")
    op.alter_column("organization", "org_id", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("raw_message", "id", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "raw_message",
        "mailbox_id",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'me'"),
    )
    op.alter_column(
        "raw_message",
        "mailbox_type",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'personal'"),
    )
    op.drop_index("idx_raw_mailbox", table_name="raw_message")
    op.drop_index("idx_raw_received", table_name="raw_message")
    op.alter_column(
        "schema_version",
        "version",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column("user", "user_id", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user_config", "user_id", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "user_config",
        "config_version",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "user_config_audit",
        "event_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.drop_index("idx_cfg_audit_user", table_name="user_config_audit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_cfg_audit_user", "user_config_audit", ["user_id"], unique=False
    )
    op.alter_column(
        "user_config_audit",
        "event_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "user_config",
        "config_version",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column("user_config", "user_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "user_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "schema_version",
        "version",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.create_index("idx_raw_received", "raw_message", ["received_dt"], unique=False)
    op.create_index(
        "idx_raw_mailbox", "raw_message", ["mailbox_id", "received_dt"], unique=False
    )
    op.alter_column(
        "raw_message",
        "mailbox_type",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'personal'"),
    )
    op.alter_column(
        "raw_message",
        "mailbox_id",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'me'"),
    )
    op.alter_column("raw_message", "id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("organization", "org_id", existing_type=sa.TEXT(), nullable=True)
    op.create_index("idx_msg_urgency", "message", ["urgency"], unique=False)
    op.create_index("idx_msg_thread", "message", ["thread_id"], unique=False)
    op.create_index("idx_message_received", "message", ["received_dt"], unique=False)
    op.alter_column(
        "message",
        "has_attachment",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "message",
        "urgency",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'none'"),
    )
    op.alter_column("message", "id", existing_type=sa.TEXT(), nullable=True)
    op.drop_constraint("uq_mbe_mb_canonical", "mailbox_emails", type_="unique")
    op.create_index(
        "idx_mb_processed", "mailbox_emails", ["processed", "created_ts"], unique=False
    )
    op.alter_column(
        "mailbox_emails",
        "processed",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "mailbox_emails",
        "seen",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "mailbox_emails",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.drop_constraint("uq_me_mb_email", "mailbox_email", type_="unique")
    op.create_index(
        "idx_mb_email_mailbox", "mailbox_email", ["mailbox_id"], unique=False
    )
    op.create_index("idx_mb_email_email", "mailbox_email", ["email_id"], unique=False)
    op.alter_column(
        "mailbox_email",
        "mailbox_email_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.create_index("idx_mailbox_org", "mailbox", ["org_id"], unique=False)
    op.alter_column("mailbox", "mailbox_id", existing_type=sa.TEXT(), nullable=True)
    op.create_index("idx_idea_tenor", "idea", ["tenor"], unique=False)
    op.create_index("idx_idea_status", "idea", ["status"], unique=False)
    op.create_index("idx_idea_product", "idea", ["product"], unique=False)
    op.create_index("idx_idea_message", "idea", ["message_id"], unique=False)
    op.create_index("idx_idea_ccy", "idea", ["ccy"], unique=False)
    op.alter_column(
        "idea",
        "extracted_by",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'rules_v1'"),
    )
    op.alter_column(
        "idea",
        "stop_level",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "idea",
        "target_level",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "idea",
        "entry_level",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "idea", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.alter_column(
        "email_flag",
        "has_extraction",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "email_flag",
        "has_translation",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "email_flag",
        "has_summary",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "email_flag", "mailbox_email_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index("idx_email_thread", "email", ["thread_id"], unique=False)
    op.create_index("idx_email_received", "email", ["received_at"], unique=False)
    op.create_index("idx_email_org", "email", ["org_id"], unique=False)
    op.alter_column("email", "email_id", existing_type=sa.TEXT(), nullable=True)
    op.create_index(
        "idx_cls_time", "classification_event", ["created_ts"], unique=False
    )
    op.create_index("idx_cls_msg", "classification_event", ["message_id"], unique=False)
    op.alter_column(
        "classification_event",
        "confidence",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "classification_event",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.drop_constraint("uq_run_mb_email_action_fp", "automation_run", type_="unique")
    op.create_index(
        "idx_run_mailbox", "automation_run", ["mailbox_id", "status"], unique=False
    )
    op.create_index("idx_run_email", "automation_run", ["email_id"], unique=False)
    op.alter_column("automation_run", "run_id", existing_type=sa.TEXT(), nullable=True)
    op.create_index("idx_att_name", "attachment", ["name"], unique=False)
    op.create_index("idx_att_msg", "attachment", ["message_id"], unique=False)
    op.alter_column("attachment", "id", existing_type=sa.TEXT(), nullable=True)
    op.create_index("idx_artifact_run", "artifact", ["run_id"], unique=False)
    op.create_index("idx_artifact_email", "artifact", ["email_id"], unique=False)
    op.alter_column("artifact", "artifact_id", existing_type=sa.TEXT(), nullable=True)
    op.create_table(
        "message_fts_docsize",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("sz", sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_fts_config",
        sa.Column("k", sa.NullType(), nullable=False),
        sa.Column("v", sa.NullType(), nullable=True),
        sa.PrimaryKeyConstraint("k"),
    )
    op.create_table(
        "message_fts_data",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("block", sa.BLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_fts_idx",
        sa.Column("segid", sa.NullType(), nullable=False),
        sa.Column("term", sa.NullType(), nullable=False),
        sa.Column("pgno", sa.NullType(), nullable=True),
        sa.PrimaryKeyConstraint("segid", "term"),
    )
    op.create_table(
        "message_fts",
        sa.Column("subject", sa.NullType(), nullable=True),
        sa.Column("body_text", sa.NullType(), nullable=True),
        sa.Column("entities", sa.NullType(), nullable=True),
    )
    # ### end Alembic commands ###
